---
# defaults file for wordpress
mysql_root_password: ''
wordpress_user_password: 12345678
dbuserhost: localhost #database-user-host, values: localhost, %
dbuser: wp-user
wpdb: wordpress
install_type: server
rdshost: localhost